app/urls.py
from django.urls import path
from .views.tarefas_views import *
from .views.usuarios_views import *

urlpatterns = [
    path('',logar_usuario, name='logar_usuario'),
    path('listar_tarefas/', listar_tarefas,name='listar_tarefas' ),
    path('cadastrar_tarefas/', cadastrar_tarefa, name='cadastrar_tarefas'),
    path('editar_tarefa/<int:id>', editar_tarefa, name='editar_tarefa'),
    path('remover_tarefa/<int:id>',remover_tarefa, name='remover_tarefa'),
    path('cadastrar_usuarios/',cadastrar_usuarios, name='cadastrar_usuarios'),
    path('logar_usuario/',logar_usuario, name='logar_usuario'),
    path('deslogar_usuario/',deslogar_usuario, name='deslogar_usuario'),

]

gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A","Alta"),
        ("N","Normal"),
        ("B", "Baixa"),
    ]
    titulo = models.CharField(max_length=30, null= False ,blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao= models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES)
    usuario = models.ForeignKey(User,null=True, on_delete=models.CASCADE)

app/forms.py
from django import forms
from .models import Tarefa


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario',)
        fields = '__all__'

app/views/tarefas_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefas import Tarefa
from ..services import tarefa_service


@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request,'tarefas/listar_tarefas.html', {"tarefas":tarefas})

@login_required()
def cadastrar_tarefa(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = Tarefa(titulo=titulo,descricao=descricao,data_expiracao=data_expiracao,
                                 prioridade=prioridade,usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa":form_tarefa})

@login_required()
def editar_tarefa(request,id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Usuario não Permitido")
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data["titulo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        tarefa_editada = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        tarefa_service.editar_tarefa(tarefa_bd,tarefa_editada)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa":form_tarefa})

@login_required()
def remover_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Usuario não Permitido")

    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return  redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa':tarefa_bd})

app/views/usuarios_views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def cadastrar_usuarios(request):
    if request.method == "POST":
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('logar_usuario')
    else:
        form_usuario = UserCreationForm()
    return render(request, 'usuarios/form_usuarios.html',{"form_usuario":form_usuario})


def logar_usuario(request):
    if request.method =="POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request,username=username,
                               password=password)
        if usuario is not None:
            login(request,usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'Suas credenciais não funcionaram, verifique seu usuario e senha')
            return redirect('logar_usuario')
    else:
       form_login = AuthenticationForm()
    return render(request, 'usuarios/login.html',{"form_login":form_login})


def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Gerenciador de Tarefas</title>
  <!-- MDB icon -->
  <link rel="icon" href="{% static 'app/img/mdb-favicon.ico' %}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'app/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
</head>
<body>

  <!-- Start your project here-->
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="#">Tarefas</a>

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Lista de Tarefas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Log out</a>
      </li>
    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Buscar..." aria-label="Procurar">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->

  <!-- End your project here-->

    <main class="container">
        {% block conteudo %}
        {% endblock conteudo %}
    </main>

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'app/js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'app/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'app/js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>
</body>
</html>

app/templates/base_bk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LISTA DE TAREFAS</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg  navbar-dark bg-primary">
  <a class="navbar-brand" href="#">GERENCIADOR DE TAREFAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>
<main class="container">
    {% block conteudo %}
    {% endblock conteudo %}
</main>

app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}

        <div class="card mb-3">
            <div class="card-header">
                CONFIRMA EXCLUSÃO DA TAREFA?
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ tarefa.titulo }} </h5>
                <p class="card-text"> {{tarefa.descricao}} </p>
                <br>
                <form  method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Excluir</button>
                </form>
            </div>
        </div>


{% endblock conteudo %}

app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form  method="post" >
    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.titulo.errors}}
        <label>Titulo:</label>
        {{ form_tarefa.titulo|addclass:'form-control'}}
    </div>
   <div class="form-group">
       {{ form_tarefa.descricao.errors}}
        <label>Descrição:</label>
        {{ form_tarefa.descricao|addclass:'form-control'}}
    </div>
   <div class="form-group">
       {{ form_tarefa.data_expiracao.errors}}
        <label>Data exp:</label>
        {{ form_tarefa.data_expiracao|addclass:'form-control'}}
    </div>
  <div class="form-group">
       {{ form_tarefa.prioridade.errors}}
        <label>Prioridade:</label>
        {{ form_tarefa.prioridade|addclass:'form-control'}}
    </div>
 <div class="form-group">
     <input type="submit" value="Salvar">
    </div>
</form>
{% endblock conteudo %}

app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}
    <h1>Olá {{ user.get_username }}, sua lista de tarefas.</h1>
    {% for tarefa in tarefas %}
        <div class="card mb-3">
            <div class="card-header">
                Prioridade: {{ tarefa.get_prioridade_display }}
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ tarefa.titulo }} </h5>
                <p class="card-text"> {{tarefa.descricao}} </p>
                <br>
                <a href="{% url 'editar_tarefa' tarefa.id %}">Editar</a>
                <a href="{% url 'remover_tarefa' tarefa.id %}">Deletar</a>
            </div>
        </div>
    {% endfor %}
<a href="{% url 'cadastrar_tarefas' %}"> <input type="button" class="btn btn-primary mb-3" value="Cadastrar Tarefa">  </a>
{% endblock conteudo %}

app/templates/usuarios/form_usuarios.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form  method="post">
   <h2> Cadastro de Usuários</h2>
   {% csrf_token %}
   <div class="form-group">
        {{ form_usuario.username.errors}}
      <label> Nome de Usuário:</label>
      {{form_usuario.username |addclass:'form-control'}}
   </div>
   <div class="form-group">
        {{ form_usuario.password1.errors}}
      <label> Senha:</label>
      {{form_usuario.password1 |addclass:'form-control'}}
   </div>
   <div class="form-group">
        {{ form_usuario.password2.errors}}
      <label> Confirmar Senha:</label>
      {{form_usuario.password2 |addclass:'form-control'}}
   </div>
   <div class="form-group">
      <input type="submit" value="Cadastrar" class="btn btn-primary">
   </div>
</form>
{% endblock conteudo %}

app/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}

<form  method="post">
   <h2> Login de Usuário</h2>
   <h6> Faça o login ou cadastre-se</h6>
   {% csrf_token %}
   {% for message in messages %}
    <div class="alert alert-danger">
      {{message}}
    </div>
   {% endfor %}
   <div class="form-group">
      <label> Nome de Usuário:</label>
      {{form_login.username |addclass:'form-control'}}
   </div>
   <div class="form-group">
      <label> Senha:</label>
      {{form_login.password |addclass:'form-control'}}
   </div>
   <div class="form-group">
      <input type="submit" value="Entrar" class="btn btn-primary">
   </div>
   <div class="form-group">
      <a href="{% url 'cadastrar_usuarios' %}"> <input type="button" class="btn btn-primary mb-3" value="Cadastrar Usuario"> </a>
   </div>
</form>
{% endblock conteudo %}